spring:
    # JPA
    jpa:
      show_sql: false
      properties:
          hibernate:
            format_sql: false

    # JWT
    jwt:
      secret: 12345678901234567890123456789012

# logging
logging:
    level:
        org:
          hibernate:
                type:
                  descriptor:
                          sql: error



