spring:
    # JPA
    jpa:
      show_sql: false
      properties:
          hibernate:
            format_sql: false

    liquibase:
      enabled: false

# logging
logging:
    level:
        org:
          hibernate:
                type:
                  descriptor:
                          sql: error




